toppings = [
  { name: 'Mozzarella' },
  { name: 'Tomatoes' },
  { name: 'Basil' },
  { name: 'Mushrooms' },
  { name: 'Pepperoni' },
  { name: 'Onions' },
  { name: 'Garlic' },
  { name: 'Parmesan' },
  { name: 'Prosciutto' },
  { name: 'Ricotta' },
  { name: 'Artichokes' },
  { name: 'Pesto' },
  { name: 'Sausage' },
  { name: 'Peppers' },
  { name: 'Olives' },
  { name: 'Anchovies' },
  { name: 'Salami' },
  { name: 'Capicola' },
  { name: 'Burrata' },
  { name: 'Gorgonzola' },
  { name: 'Fennel sausage' },
  { name: 'Eggplant' },
  { name: 'Zucchini' },
  { name: 'Broccoli rabe' },
  { name: 'Pancetta' },
  { name: 'Clams' },
  { name: 'Mussels' },
  { name: 'Taleggio' },
  { name: 'Fontina' },
  { name: 'Goat cheese' },
  { name: 'Gruyere' },
  { name: 'Caramelized onions' },
  { name: 'Arugula' },
  { name: 'Figs' },
  { name: 'Truffle oil' },
  { name: 'Bresaola' },
  { name: 'Soppressata' },
  { name: 'Sun-dried tomatoes' },
  { name: 'Pine nuts' },
  { name: 'Pancetta' },
  { name: 'Asparagus' },
  { name: 'Porcini mushrooms' },
  { name: 'Balsamic glaze' },
  { name: 'Capers' },
  { name: 'Radicchio' },
  { name: 'Gorgonzola dolce' },
  { name: 'Pecorino' },
  { name: 'Rapini' },
  { name: 'Cherry tomatoes' },
  { name: 'Speck' },
  { name: 'Nduja' },
  { name: 'Calabrian chili' }
]

# Create toppings
Topping.create!(toppings)